4"}
name: SkillSwap Docker CI

on:
  push:
    branches:
      - main

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t skillswap-app .

      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 --name test-container skillswap-app
          sleep 5

      - name: Test App
        run: curl http://127.0.0.1:5000 || exi